namespace Aegis.Passkeys.Windows.Structures;

internal enum WEBAUTHN_API_VERSION : uint
{
    WEBAUTHN_API_VERSION_1 = 1,
    WEBAUTHN_API_VERSION_2 = 2,
    WEBAUTHN_API_VERSION_3 = 3,
    WEBAUTHN_API_VERSION_4 = 4,
    WEBAUTHN_API_VERSION_5 = 5,
    WEBAUTHN_API_VERSION_6 = 6,
    WEBAUTHN_API_VERSION_7 = 7,
    WEBAUTHN_API_VERSION_8 = 8,

    WEBAUTHN_API_CURRENT_VERSION = WEBAUTHN_API_VERSION_8,
}
