namespace Aegis.Passkeys;

/// <summary>
/// The response from a call to <see cref="PasskeyManager.GetHmacSecret"/>.
/// </summary>
public class GetHmacSecretResponse : IDisposable
{
    /// <summary>
    /// The secret generated by the authenticator, corresponding to the first input salt.
    /// </summary>
    public required HmacSecret First { get; init; }

    /// <summary>
    /// The secret generated by the authenticator, corresponding to the second input salt.
    /// </summary>
    /// <remarks>
    /// Note that second input salt is optional, and this property may be null if no second salt was provided.
    /// </remarks>
    public HmacSecret? Second { get; init; }

    #region IDisposable Implementation

    private bool isDisposed = false;

    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!isDisposed)
        {
            if (disposing)
            {
                this.First?.Dispose();
                this.Second?.Dispose();
            }

            isDisposed = true;
        }
    }

    #endregion
}
