namespace Aegis.Passkeys;

/// <summary>
/// The response from a call to <see cref="PasskeyManager.MakeCredentialWithHmacSecret"/>.
/// </summary>
public class MakeCredentialResponse
{
    /// <summary>
    /// The identifier of the newly created credential.
    /// </summary>
    public required Identifier NewCredentialId { get; init; }

    /// <summary>
    /// The secret generated by the authenticator, corresponding to the first input salt (if provided).
    /// </summary>
    /// <remarks>
    /// Note that salts are optional for MakeCredential calls, and this property may be null if no salt was provided.
    /// </remarks>
    public HmacSecret? FirstHmac { get; init; }

    /// <summary>
    /// The secret generated by the authenticator, corresponding to the second input salt (if provided).
    /// </summary>
    /// <remarks>
    /// Note that salts are optional for MakeCredential calls, and this property may be null if no second salt was provided.
    /// </remarks>
    public HmacSecret? SecondHmac { get; init; }
}
